### ISSUE TITLE
Insert of #sql-null results in error?

### ISSUE THREAD

**Issue by jadudm** [rmculpepper/sql#14]
I will try and come back around to generate a minimum working example, but it does require a MySQL DB running. I have not tried this with other backends.

Around line 315 of connection.rkt, I had to make the following patch:

[params (for/list ([p (in-list (statement-binding-params stmt))])
                              (if (sql-null? p) (cons 'null  p) p))
                            ]

Somehow, #<sql-null> is coming through through the statement-binding-params without being pairified. So, if I 

(sql (insert #:into ... #:set [a ,value-that-evaluates-to-sql-null]))

it seems like that causes problems. It may be I'm using the library incorrectly.

**Comment by rmculpepper** [comment]
Thanks for the report! Yes, that's a bug in the db library. I've pushed a fix (nearly the same as your patch above), but I don't have a mysql instance handy for testing right now. Please let me know if there's a problem with the fix.
