### ISSUE TITLE
Looking for a way to add IF NOT EXISTS and OR IGNORE to statements

### ISSUE THREAD

**Issue by DarrenN** [rmculpepper/sql#5]
I was converting a project over to using this very handy library but ran into a small snag. I currently create SQLite3 tables using the following statements:

```sql
CREATE TABLE IF NOT EXISTS links (foo integer ...);
```
And also do inserts with:

```sql
INSERT OR IGNORE INTO links (url, ...) values (?, ...)
```

Digging through the docs and experimenting with the REPL I couldn't find a way to get `IF NOT EXISTS` and `OR IGNORE` into a `sql-statement?`.

**Comment by rmculpepper** [comment]
I've just added support for these two features.

    (create-table #:if-not-exists name ....)
    (insert #:into dest #:set .... #:or-ignore)

(In general, I haven't decided how to support nonstandard extensions, but since both of these features exist in all of the big three systems, I just went ahead and added them.)

**Comment by DarrenN** [comment]
Updated the package and it worked great!
