### ISSUE TITLE
Left Joins

### ISSUE THREAD

**Issue by chutcheson** [rmculpepper/sql#6]
I was looking at the documentation describing left joins [on the racket website](https://docs.racket-lang.org/sql/index.html). It looks to me like I need to provide two tables to do a left join. It seems to look this way in the source too:

`(struct table-expr:join (type t1 t2 on) #:prefab)`

Is there a way to do a MySQL statement like the following?

```
select people 
from population 
left join tax_codes on population.areacode = tax_codes.areacode 
left join tax_rate on tax_codes.rateID = tax_rate.rateID
```

It looks to me like if I write:

`
(select people #:from (left-join population tax_codes #:on (= population.areacode tax_codes.areacode)) (left-join tax_codes tax_rate #:on (= tax_codes.rateID tax_rate.rateID)))`

I get:

`SELECT people FROM population LEFT OUTER JOIN tax_codes ON (population.areacode = tax_rate.areacode), tax_codes LEFT OUTER JOIN tax_rate ON (tax_codes.rateID = tax_rate.rateID)`

Which I don't think is a valid MySQL statement. I might be confused, though.

I think the problem might be the part here:

> _, tax_codes_ LEFT OUTER JOIN

**Comment by rmculpepper** [comment]
Your example is a left join where one of the sources is also a left join. (Joins are binary operators on table expressions.) You can write it like this:

    (select people
            #:from (left-join
                    (left-join population taxcodes
                               #:on (= population.areacode taxcodes.areacode))
                    tax_rates
                    #:on (= taxcodes.rateID tax_rates.rateID)))

which produces (formatted for email)

    SELECT people 
    FROM population
    LEFT OUTER JOIN taxcodes ON (population.areacode = taxcodes.areacode) 
    LEFT OUTER JOIN tax_rates ON (taxcodes.rateID = tax_rates.rateID)

**Comment by chutcheson** [comment]
Thank you, I can't believe I didn't think of that!
