### ISSUE TITLE
ScalarExpr:AST triggers internal unbound identifier error 

### ISSUE THREAD

**Issue by LiberalArtist** [rmculpepper/sql#7]
The following program:
```racket
#lang racket

(require sql)

(select * 
        #:from t
        #:where (ScalarExpr:AST ,'(= x 1)))
```
produces the error, "../../Applications/Racket v7.0/share/pkgs/sql/private/parse.rkt:446:55: scalar-expr?: unbound identifier".

Is it perhaps supposed to be `scalar-expr-ast?`?

**Comment by rmculpepper** [comment]
Indeed, thanks for the report!
